---


R1:
    hostname: 192.168.31.201
    platform: 'ios'
    username: john
    password: ciscoooo
    groups:
        - cisco_group
    data:
        domain: ipvzero

R2:
    hostname: 192.168.31.202
    platform: 'ios'
    username: john
    password: cisco
    groups:
        - cisco_group
    data:
        domain: ipvzero
        asn: 99
